### ISSUE TITLE
YouTube-API non-free?

### ISSUE THREAD

**Issue by krt16s** [janoliver/pOT-Droid#281]
You reference ` compile files('libs/YouTubeAndroidPlayerApi.jar')`, but it is git-ignored. This is most likely the proprietary API-Jar, so could you provide a gradle build flavor that does not depend on it?

**Comment by janoliver** [comment]
Hi, it is free so I added it to the repo including a custom license. See https://github.com/janoliver/pOT-Droid/tree/master/libs .

**Comment by krt16s** [comment]
I meant free as in freedom, not gratis. So it's proprietary, no source available. Sigh. Any changes providing a pure-floss build with functionality removed?

**Comment by janoliver** [comment]
Alright, sorry for the misunderstanding. I assume this is for the projects's FDroid build? 

I'll figure something out until the 5.0 release. Note, that the current release listed on Github is a pre-release only.

**Comment by janoliver** [comment]
I removed the feature and library completely in b24f0c5d9b72ef5348021f90f6e55718e4369e5d.

**Comment by krt16s** [comment]
Yup, builds again, thanks for the quick response!
