### ISSUE TITLE
Chrome custom tabs unterstuetzen

### ISSUE THREAD

**Issue by janfreyberg** [janoliver/pOT-Droid#286]
Chrome custom tabs als option fuer Links einbauen waere cool, besonders mit den "warm-up" funktionen.

Dachte mir dass das ganz cool waere, und nicht schwer einzubauen ist (?). Wenn du mir ein paar pointer gibst wuerde ich das mal versuchen.

**Comment by janoliver** [comment]
Habe es eingebaut.

**Comment by janfreyberg** [comment]
Super, danke! Hatte es aus den Augen verloren, tut mir leid.
